"use client";
import Link from "next/link";
import { FormEvent, useEffect, useState } from "react";
import { ArrowLeft, BriefcaseBusiness, Plus, ShoppingBag, Wrench } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { NativeSelect, NativeSelectOption } from "@/components/ui/native-select";
type Workspace={id:string;name:string;mode:string;role:string};
const modes={store:ShoppingBag,services:Wrench,portfolio:BriefcaseBusiness};
export function BusinessManager(){const[list,setList]=useState<Workspace[]>([]),[active,setActive]=useState(""),[name,setName]=useState(""),[mode,setMode]=useState("store"),[saving,setSaving]=useState(false);const load=()=>fetch("/api/workspace").then(r=>r.json()).then(d=>{setList(d.workspaces||[]);setActive(d.workspace?.id||"")});useEffect(()=>{load()},[]);const choose=async(id:string)=>{await fetch("/api/workspace",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:id})});location.href="/dashboard"};const create=async(e:FormEvent)=>{e.preventDefault();setSaving(true);await fetch("/api/workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,mode})});location.href="/dashboard"};return <main className="min-h-screen bg-[#f3f4ef] p-5 lg:p-8"><div className="mx-auto max-w-5xl"><header className="flex items-center gap-4"><Button asChild size="icon" variant="outline" className="rounded-xl"><Link href="/dashboard"><ArrowLeft className="size-4"/></Link></Button><div><p className="text-xs uppercase tracking-wider text-black/40">Your account</p><h1 className="text-2xl font-semibold">Businesses</h1></div></header><div className="mt-7 grid gap-6 lg:grid-cols-[1fr_360px]"><section className="rounded-2xl border border-black/8 bg-white p-5"><h2 className="font-semibold">Your workspaces</h2><div className="mt-4 space-y-3">{list.map(w=>{const Icon=modes[w.mode as keyof typeof modes]||BriefcaseBusiness;return <button onClick={()=>choose(w.id)} key={w.id} className={`flex w-full items-center gap-4 rounded-xl border p-4 text-left ${active===w.id?"border-[#173a2b] bg-[#eff5f1]":"border-black/8"}`}><span className="grid size-10 place-items-center rounded-xl bg-white"><Icon className="size-4"/></span><span className="flex-1"><strong className="block">{w.name}</strong><small className="capitalize text-black/45">{w.mode} · {w.role}</small></span>{active===w.id&&<span className="text-xs font-medium text-[#286044]">Active</span>}</button>})}</div></section><form onSubmit={create} className="h-fit rounded-2xl border border-black/8 bg-white p-5"><h2 className="font-semibold">Create another business</h2><div className="mt-5 space-y-4"><Input required value={name} onChange={e=>setName(e.target.value)} placeholder="Business name" className="rounded-xl"/><NativeSelect value={mode} onChange={e=>setMode(e.target.value)} className="w-full rounded-xl"><NativeSelectOption value="store">Online store</NativeSelectOption><NativeSelectOption value="services">Service business</NativeSelectOption><NativeSelectOption value="portfolio">Portfolio & CV</NativeSelectOption></NativeSelect><Button disabled={saving} className="w-full rounded-xl bg-[#173a2b]"><Plus className="size-4"/>{saving?"Creating…":"Create business"}</Button></div></form></div></div></main>}
