"use client";
import {FormEvent,useEffect,useState} from "react";
import {BriefcaseBusiness,Check,Plus,ShoppingBag,Wrench} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
import {NativeSelect,NativeSelectOption} from "@/components/ui/native-select";
import {invalidateWorkspace} from "@/lib/client/workspace";
type Workspace={id:string;name:string;mode:string;role:string;workspaceType?:string};
type WorkspaceType="commerce_business"|"business_showcase"|"cv"|"portfolio";
const icons={store:ShoppingBag,services:Wrench,portfolio:BriefcaseBusiness};
const labels:Record<WorkspaceType,string>={commerce_business:"Commerce business",business_showcase:"Business showcase",cv:"CV website",portfolio:"Portfolio website"};
async function json(response:Response){const data=await response.json().catch(()=>({error:"The server returned an invalid response"}));if(!response.ok)throw new Error(data.error||"Request failed");return data;}
export function BusinessManager(){
  const[list,setList]=useState<Workspace[]>([]),[active,setActive]=useState(""),[name,setName]=useState("");
  const[type,setType]=useState<WorkspaceType>("commerce_business"),[category,setCategory]=useState("");
  const[website,setWebsite]=useState(true),[pos,setPos]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState("");
  const load=()=>fetch("/api/workspace").then(json).then(d=>{setList(d.workspaces||[]);setActive(d.workspace?.id||"")}).catch(reason=>setError(reason instanceof Error?reason.message:"Could not load workspaces"));
  useEffect(()=>{void load()},[]);
  const choose=async(id:string)=>{setError("");try{await fetch("/api/workspace",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({workspaceId:id})}).then(json);invalidateWorkspace();location.assign("/dashboard");}catch(reason){setError(reason instanceof Error?reason.message:"Could not switch workspace");}};
  const create=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError("");const services=type==="commerce_business"?[website?"ecommerce_website":null,pos?"pos":null].filter(Boolean):[type];try{await fetch("/api/workspace",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,slug:name,type,businessCategory:category,requestId:crypto.randomUUID(),services})}).then(json);invalidateWorkspace();location.assign("/dashboard");}catch(reason){setError(reason instanceof Error?reason.message:"Could not create workspace");setSaving(false);}};
  return <main className="admin-page"><header className="admin-page-header"><div><p>Account</p><h1>Businesses</h1><span>Own multiple workspaces and switch between them at any time.</span></div></header>
    {error?<div className="mb-4 rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{error}</div>:null}
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_360px]"><section className="admin-card p-4"><div className="flex items-center justify-between border-b border-black/8 pb-4"><div><h2>Your businesses</h2><p className="mt-1 text-xs text-black/40">{list.length} workspace{list.length===1?"":"s"}</p></div></div><div className="mt-3 grid gap-2">{list.map(w=>{const Icon=icons[w.mode as keyof typeof icons]||BriefcaseBusiness;return <button type="button" onClick={()=>void choose(w.id)} key={w.id} className={`flex w-full items-center gap-3 rounded-lg border p-3 text-left transition ${active===w.id?"border-[#294b34] bg-[#f0f4f0]":"border-black/10 hover:bg-black/[.015]"}`}><span className="grid size-9 place-items-center rounded-md bg-white shadow-sm"><Icon className="size-4"/></span><span className="min-w-0 flex-1"><strong className="block truncate text-xs">{w.name}</strong><small className="capitalize text-[10px] text-black/40">{w.workspaceType?labels[w.workspaceType as WorkspaceType]||w.workspaceType:w.mode} · {w.role}</small></span>{active===w.id&&<span className="flex items-center gap-1 text-[10px] font-semibold text-[#315b3d]"><Check className="size-3"/>Active</span>}</button>})}</div></section>
      <form onSubmit={create} className="admin-card h-fit p-4"><h2>Create another workspace</h2><p className="mt-1 text-xs text-black/40">Each workspace keeps its own services, content and website.</p><div className="mt-5 space-y-3"><label className="block text-[11px] font-semibold">Workspace name<Input required value={name} onChange={e=>setName(e.target.value)} placeholder="Workspace name" className="mt-1.5"/></label><label className="block text-[11px] font-semibold">Workspace type<NativeSelect value={type} onChange={e=>setType(e.target.value as WorkspaceType)} className="mt-1.5 w-full"><NativeSelectOption value="commerce_business">Commerce business</NativeSelectOption><NativeSelectOption value="business_showcase">Business showcase</NativeSelectOption><NativeSelectOption value="cv">CV website</NativeSelectOption><NativeSelectOption value="portfolio">Portfolio website</NativeSelectOption></NativeSelect></label>
      {(type==="commerce_business"||type==="business_showcase")?<label className="block text-[11px] font-semibold">Business category<Input required value={category} onChange={e=>setCategory(e.target.value)} placeholder="e.g. Jewellery, salon, consulting" className="mt-1.5"/></label>:null}
      {type==="commerce_business"?<fieldset className="rounded-xl border border-black/10 p-3"><legend className="px-1 text-[11px] font-semibold">Services to activate</legend><label className="flex items-center gap-2 py-1 text-xs"><input type="checkbox" checked={website} onChange={e=>setWebsite(e.target.checked)}/>Ecommerce website</label><label className="flex items-center gap-2 py-1 text-xs"><input type="checkbox" checked={pos} onChange={e=>setPos(e.target.checked)}/>Point of Sale</label></fieldset>:null}
      <Button disabled={saving||(type==="commerce_business"&&!website&&!pos)} className="admin-primary w-full"><Plus className="size-4"/>{saving?"Creating…":"Create workspace"}</Button></div></form></div></main>;
}
