"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { BarChart3, Box, CalendarDays, ChevronRight, Globe2, Home, Inbox as InboxIcon, Layers3, Palette, Settings, ShoppingBag, Sparkles, Users } from "lucide-react";
import { Button } from "@/components/ui/button";

type Summary={items:number;requests:number;customers:number;unread:number};
export function Dashboard(){
 const[mode,setMode]=useState("store"),[name,setName]=useState("North & Pine Studio"),[slug,setSlug]=useState(""),[userName,setUserName]=useState("there"),[status,setStatus]=useState("draft"),[summary,setSummary]=useState<Summary>({items:0,requests:0,customers:0,unread:0}),[loading,setLoading]=useState(true);
 useEffect(()=>{fetch("/api/workspace").then(r=>r.json()).then(d=>{if(d.workspace){setMode(d.workspace.mode);setName(d.workspace.name);setSlug(d.workspace.slug)}if(d.user)setUserName(d.user.displayName?.split(" ")[0]||d.user.email);if(d.page)setStatus(d.page.status);if(d.summary)setSummary(d.summary)}).finally(()=>setLoading(false))},[]);
 const special=mode==="store"?{icon:ShoppingBag,label:"Products & orders"}:mode==="services"?{icon:CalendarDays,label:"Services & bookings"}:{icon:Box,label:"Projects & CV"};
 const nav=[{icon:Home,label:"Overview",href:"/dashboard",active:true},{icon:Layers3,label:"Website builder",href:"/builder"},{icon:Palette,label:"Themes",href:"/themes"},{icon:special.icon,label:special.label,href:"/content"},{icon:InboxIcon,label:"Customer inbox",href:"/inbox",badge:summary.unread},{icon:Users,label:"Customers",href:"/inbox"},{icon:BarChart3,label:"Analytics",href:"/dashboard"}];
 const activityLabel=mode==="store"?"Orders":mode==="services"?"Bookings":"Enquiries";
 return <main className="min-h-screen bg-[#f3f4ef] text-[#1b1d19] lg:grid lg:grid-cols-[240px_1fr]">
  <aside className="hidden border-r border-black/10 bg-[#f6f6f7] p-4 text-[#202223] lg:flex lg:flex-col"><div className="flex items-center gap-3 px-2 font-semibold"><span className="grid size-8 place-items-center rounded-lg bg-[#303030] text-sm text-white">M</span>Modulo</div><div className="mt-6 rounded-lg border border-black/8 bg-white p-3 shadow-sm"><p className="text-[10px] font-semibold tracking-wide text-black/40">CURRENT BUSINESS</p><p className="mt-1 truncate text-sm font-medium">{name}</p><p className="mt-0.5 text-[11px] capitalize text-black/45">{mode} mode</p></div><nav className="mt-4 space-y-0.5">{nav.map(({icon:Icon,label,href,active,badge})=><Link href={href} key={label} className={`flex w-full items-center gap-3 rounded-lg px-3 py-2 text-sm ${active?"bg-[#e3e3e3] font-medium text-[#202223]":"text-black/65 hover:bg-[#ebebeb]"}`}><Icon className="size-4"/><span className="flex-1">{label}</span>{badge? <span className="grid min-w-5 place-items-center rounded-full bg-[#303030] px-1 text-[10px] font-semibold text-white">{badge}</span>:null}</Link>)}</nav><button className="mt-auto flex items-center gap-3 rounded-lg px-3 py-2 text-sm text-black/60 hover:bg-[#ebebeb]"><Settings className="size-4"/>Settings</button></aside>
  <section><header className="flex min-h-18 flex-wrap items-center justify-between gap-3 border-b border-black/8 bg-white px-5 py-3 lg:px-8"><div><p className="text-xs text-black/40">BUSINESS OVERVIEW</p><h1 className="text-lg font-semibold">Good morning, {userName}</h1></div><div className="flex flex-wrap gap-2"><Button asChild variant="outline" className="rounded-xl"><Link href="/businesses">Switch business</Link></Button><Button asChild variant="outline" className="rounded-xl"><Link href="/themes"><Palette className="size-4"/>Choose theme</Link></Button><Button asChild variant="outline" className="rounded-xl"><Link href="/inbox"><InboxIcon className="size-4"/>Inbox{summary.unread>0&&` (${summary.unread})`}</Link></Button><Button asChild variant="outline" className="rounded-xl"><Link href={slug?`/s/${slug}`:"/site"}><Globe2 className="size-4"/>View site</Link></Button><Button asChild className="rounded-xl bg-[#173a2b] hover:bg-[#10291f]"><Link href="/builder"><Sparkles className="size-4"/>Edit website</Link></Button></div></header>
  <div className="mx-auto max-w-6xl p-5 lg:p-8"><div className="rounded-[1.6rem] bg-[#dcecdf] p-6 lg:flex lg:items-center lg:justify-between lg:p-8"><div><p className="text-sm font-medium text-[#286044]">YOUR WEBSITE · <span className="uppercase">{status}</span></p><h2 className="mt-2 text-3xl font-semibold tracking-tight">Your business is taking shape.</h2><p className="mt-2 text-sm text-black/55">{summary.items} {mode==="store"?"products":mode==="services"?"services":"projects"} and {summary.requests} customer requests are connected to your site.</p></div><Button asChild className="mt-5 rounded-xl bg-[#173a2b] lg:mt-0"><Link href="/builder">Open website builder <ChevronRight className="size-4"/></Link></Button></div>
  <div className="mt-6 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[["Website status",status,"Saved page",Layers3],[mode==="store"?"Products":mode==="services"?"Services":"Projects",summary.items,"Live content",special.icon],[activityLabel,summary.requests,`${summary.unread} new`,InboxIcon],["Customers",summary.customers,"Unique contacts",Users]].map(([a,b,c,I]:any)=><Link href={a==="Website status"?"/builder":a==="Customers"||a===activityLabel?"/inbox":"/content"} key={a} className="rounded-2xl border border-black/8 bg-white p-5 transition hover:-translate-y-0.5 hover:shadow-md"><div className="flex items-center justify-between"><p className="text-sm text-black/45">{a}</p><I className="size-4 text-black/30"/></div><p className={`mt-5 text-3xl font-semibold ${loading?"animate-pulse text-black/20":"capitalize"}`}>{loading?"—":b}</p><p className="mt-1 text-xs text-black/40">{c}</p></Link>)}</div>
  <div className="mt-6 rounded-2xl border border-black/8 bg-white p-5"><div className="flex items-center justify-between"><h3 className="font-semibold">Quick actions</h3><span className="text-xs text-black/35">All buttons are now connected</span></div><div className="mt-5 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Link href="/themes" className="flex items-center gap-3 rounded-xl bg-[#eef3ef] p-4"><span className="grid size-7 place-items-center rounded-full bg-white"><Palette className="size-3.5"/></span><span className="text-sm font-medium">Choose website theme</span></Link><Link href="/builder" className="flex items-center gap-3 rounded-xl bg-[#f5f5f1] p-4"><span className="grid size-7 place-items-center rounded-full bg-white text-xs font-semibold">1</span><span className="text-sm">Customise homepage</span></Link><Link href="/content" className="flex items-center gap-3 rounded-xl bg-[#f5f5f1] p-4"><span className="grid size-7 place-items-center rounded-full bg-white text-xs font-semibold">2</span><span className="text-sm">Manage {mode==="store"?"products":mode==="services"?"services":"projects"}</span></Link><Link href="/inbox" className="flex items-center gap-3 rounded-xl bg-[#f5f5f1] p-4"><span className="grid size-7 place-items-center rounded-full bg-white text-xs font-semibold">3</span><span className="text-sm">Review customer requests</span></Link></div></div></div></section>
 </main>
}
