"use client";
/* eslint-disable react-hooks/set-state-in-effect -- the initial API snapshot populates this client-side manager */
import Link from "next/link";
import {FormEvent,useCallback,useEffect,useState} from "react";
import {Copy,ExternalLink,FileText,Plus,Send,Trash2} from "lucide-react";
import {Button} from "@/components/ui/button";
import {Input} from "@/components/ui/input";
type Page={id:string;title:string;slug:string;status:string;updatedAt:number};
type Menu={id:string;handle:string;name:string};
type MenuItem={id:string;menuId:string;parentId?:string|null;label:string;url:string;position:number};
async function json(response:Response){const data=await response.json().catch(()=>({error:"The server returned an invalid response"}));if(!response.ok)throw new Error(data.error||"Request failed");return data;}
export function PagesManager(){
  const[pages,setPages]=useState<Page[]>([]),[title,setTitle]=useState(""),[saving,setSaving]=useState(false);
  const[workspaceSlug,setWorkspaceSlug]=useState(""),[menu,setMenu]=useState<Menu|null>(null),[items,setItems]=useState<MenuItem[]>([]);
  const[busy,setBusy]=useState(""),[message,setMessage]=useState(""),[error,setError]=useState("");
  const load=useCallback(async()=>{try{const[pageData,workspaceData,navigationData]=await Promise.all([fetch("/api/pages").then(json),fetch("/api/workspace").then(json),fetch("/api/site/navigation").then(json)]);setPages(pageData.pages||[]);setWorkspaceSlug(workspaceData.workspace?.slug||"");const main=(navigationData.menus||[]).find((entry:Menu)=>entry.handle==="main")||null;setMenu(main);setItems(main?(navigationData.items||[]).filter((item:MenuItem)=>item.menuId===main.id):[]);}catch(reason){setError(reason instanceof Error?reason.message:"Could not load pages");}},[]);
  useEffect(()=>{void load()},[load]);
  const create=async(e:FormEvent)=>{e.preventDefault();setSaving(true);setError("");try{const page=await fetch("/api/pages",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({title})}).then(json);location.assign(`/builder?page=${encodeURIComponent(page.slug)}`);}catch(reason){setError(reason instanceof Error?reason.message:"Could not create page");setSaving(false);}};
  const act=async(page:Page,action:"duplicate"|"publish"|"unpublish"|"delete")=>{if(action==="delete"&&!confirm(`Delete “${page.title}”? This cannot be undone.`))return;setBusy(`${page.id}:${action}`);setError("");setMessage("");try{const url=action==="duplicate"?`/api/pages/${page.id}/duplicate`:action==="delete"?`/api/pages/${page.id}`:`/api/pages/${page.id}/publish`;await fetch(url,{method:action==="unpublish"||action==="delete"?"DELETE":"POST"}).then(json);setMessage(action==="duplicate"?"Page duplicated.":action==="publish"?"Page published.":action==="unpublish"?"Page unpublished.":"Page deleted.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Action failed");}finally{setBusy("");}};
  const inMenu=(page:Page)=>items.some(item=>item.url===(page.slug==="home"?"/":`/${page.slug}`));
  const toggleMenu=async(page:Page)=>{setBusy(`${page.id}:menu`);setError("");try{const url=page.slug==="home"?"/":`/${page.slug}`;const wasIncluded=inMenu(page);const next=wasIncluded?items.filter(item=>item.url!==url):[...items,{id:crypto.randomUUID(),menuId:menu?.id||"",label:page.title,url,position:items.length}];await fetch("/api/site/navigation",{method:"PUT",headers:{"content-type":"application/json"},body:JSON.stringify({handle:"main",name:menu?.name||"Main menu",items:next.map(({id,parentId,label,url},position)=>({id,parentId,label,url,position}))})}).then(json);setMessage(wasIncluded?"Removed from the website menu.":"Added to the website menu.");await load();}catch(reason){setError(reason instanceof Error?reason.message:"Could not update navigation");}finally{setBusy("");}};
  const liveHref=(page:Page)=>workspaceSlug?`/s/${workspaceSlug}${page.slug==="home"?"":`/${page.slug}`}`:"";
  return <main className="admin-page"><header className="admin-page-header"><div><p>Website structure</p><h1>Pages</h1><span>Create, publish, duplicate and place pages in your website menu.</span></div>{workspaceSlug?<Button asChild variant="outline"><Link href={`/s/${workspaceSlug}`} target="_blank"><ExternalLink/>View website</Link></Button>:null}</header>
    {(error||message)&&<div className={`mb-4 rounded-xl border px-4 py-3 text-sm ${error?"border-red-200 bg-red-50 text-red-700":"border-green-200 bg-green-50 text-green-800"}`}>{error||message}</div>}
    <div className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_300px]"><section className="admin-card p-4"><div className="divide-y">{pages.map(page=><article key={page.id} className="flex flex-wrap items-center gap-3 px-2 py-4"><span className="admin-icon"><FileText/></span><span className="min-w-40 flex-1"><strong className="block text-sm">{page.title}</strong><small className="text-black/45">/{page.slug==="home"?"":page.slug} · {page.status}</small></span><label className="flex items-center gap-2 text-xs"><input type="checkbox" checked={inMenu(page)} disabled={busy.startsWith(`${page.id}:`)} onChange={()=>void toggleMenu(page)}/>Show in menu</label><div className="flex flex-wrap gap-1"><Button asChild size="sm" variant="outline"><Link href={`/builder?page=${encodeURIComponent(page.slug)}`}>Edit</Link></Button>{page.status==="published"&&liveHref(page)?<Button asChild size="icon" variant="outline"><Link aria-label="View live page" href={liveHref(page)} target="_blank"><ExternalLink/></Link></Button>:null}<Button aria-label="Duplicate page" size="icon" variant="outline" disabled={busy.startsWith(`${page.id}:`)} onClick={()=>void act(page,"duplicate")}><Copy/></Button><Button aria-label={page.status==="published"?"Unpublish page":"Publish page"} size="icon" variant="outline" disabled={busy.startsWith(`${page.id}:`)} onClick={()=>void act(page,page.status==="published"?"unpublish":"publish")}><Send/></Button>{page.slug!=="home"?<Button aria-label="Delete page" size="icon" variant="outline" className="text-red-600" disabled={busy.startsWith(`${page.id}:`)} onClick={()=>void act(page,"delete")}><Trash2/></Button>:null}</div></article>)}</div></section>
      <form onSubmit={create} className="admin-card h-fit p-4"><h2>New page</h2><p className="mb-4">Create a page, then choose whether it appears in the main menu.</p><Input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="Page title"/><Button disabled={saving} className="admin-primary mt-3 w-full"><Plus/>{saving?"Creating…":"Create page"}</Button></form></div></main>;
}
