import{createSection}from"@/lib/builder/registry";import type{PageDocument,PageSection,PageType}from"./page-document";import{validatePageDocument}from"./page-document";
export const guidedPageDefinitions=[{slug:"home",title:"Home",pageType:"home"},{slug:"products",title:"Products",pageType:"collection"},{slug:"product",title:"Product template",pageType:"product"},{slug:"collections",title:"Collections",pageType:"collection"},{slug:"collection",title:"Collection template",pageType:"collection"},{slug:"search",title:"Search",pageType:"standard"},{slug:"cart",title:"Cart",pageType:"standard"},{slug:"policies",title:"Store policies",pageType:"standard"}]as const;
export type GuidedStorefrontInput={businessType:string;brandName:string;tagline:string;accentColor:string;featuredProductIds:string[];featuredCollectionIds:string[];desiredContent:string[];publish:boolean};
const text=(value:unknown,max=120)=>String(value||"").trim().slice(0,max),ids=(value:unknown)=>Array.isArray(value)?[...new Set(value.filter(item=>typeof item==="string").map(item=>item.slice(0,100)))].slice(0,24):[];
export function validateGuidedStorefrontInput(value:unknown):GuidedStorefrontInput{if(!value||typeof value!=="object"||Array.isArray(value))throw new Error("Storefront setup is required");const input=value as Record<string,unknown>,brandName=text(input.brandName);if(!brandName)throw new Error("Brand name is required");const accentColor=text(input.accentColor,20)||"#173a2b";if(!/^#[0-9a-fA-F]{6}$/.test(accentColor))throw new Error("Accent colour must be a six-digit hex colour");return{businessType:text(input.businessType,80)||"Retail",brandName,tagline:text(input.tagline,180)||`Discover ${brandName}`,accentColor,featuredProductIds:ids(input.featuredProductIds),featuredCollectionIds:ids(input.featuredCollectionIds),desiredContent:ids(input.desiredContent),publish:Boolean(input.publish)}}
const section=(type:string,settings:Record<string,string|number|boolean|null>={})=>{const created=createSection(type,0);return{...created,settings:{...created.settings,...settings},blocks:created.blocks||[]}as PageSection};
export function createGuidedPageDocument(input:GuidedStorefrontInput,slug:string):PageDocument{const common={schemaVersion:2 as const,editorMode:"guided"as const,globalTokens:{brandName:input.brandName,accentColor:input.accentColor,businessType:input.businessType},dataSources:{products:{role:"catalog.products",query:{status:"active",ids:input.featuredProductIds.join(",")}},collections:{role:"catalog.collections",query:{status:"active",ids:input.featuredCollectionIds.join(",")}}}};let sections:PageSection[];if(slug==="home")sections=[section("hero",{eyebrow:input.businessType,heading:input.brandName,body:input.tagline,buttonLabel:"Shop now",buttonUrl:"/products"}),section("product-showcase",{heading:"Featured products",body:"Automatically updated from your active catalogue."}),section("features",{heading:"Why shop with us"}),section("callout",{heading:"Explore the collection",body:"Find something selected for you."})];else if(slug==="products"||slug==="product"||slug==="search")sections=[section("hero",{heading:slug==="search"?"Search":slug==="product"?"Product details":"All products",body:"Live products from our catalogue."}),section("product-showcase",{heading:slug==="search"?"Search results":slug==="product"?"Selected product":"Shop all",body:"Availability and pricing update automatically."})];else if(slug==="collections"||slug==="collection")sections=[section("hero",{heading:slug==="collection"?"Collection details":"Collections",body:"Browse curated collections."}),section("product-showcase",{heading:"Featured collections",body:"Collections update automatically from the catalogue."})];else if(slug==="cart")sections=[section("hero",{heading:"Your cart",body:"Review your selected products before checkout."}),section("callout",{heading:"Continue shopping",body:"Your catalogue is always available."})];else sections=[section("hero",{heading:"Store policies",body:`Important information from ${input.brandName}.`}),section("flexible-content",{heading:"Shipping, returns and privacy",body:"Add your policy details here before launch."})];return validatePageDocument({...common,sections})}
export function guidedCompleteness(input:GuidedStorefrontInput,activeProducts:number,generatedSlugs:string[]){const checks=[{id:"brand",label:"Brand details",complete:Boolean(input.brandName&&input.tagline)},{id:"products",label:"Active products",complete:activeProducts>0},{id:"pages",label:"Required storefront pages",complete:guidedPageDefinitions.every(page=>generatedSlugs.includes(page.slug))},{id:"policies",label:"Policy page",complete:generatedSlugs.includes("policies")}];return{checks,complete:checks.every(check=>check.complete),score:Math.round(checks.filter(check=>check.complete).length/checks.length*100)}}
export type GuidedPageDefinition={slug:string;title:string;pageType:PageType};
