import type { ComponentType } from "react";
export type SettingValue=string|number|boolean|null;export type ComponentSettings=Record<string,SettingValue>;
export type SiteBlock={id:string;type:string;version?:number;settings:ComponentSettings;blocks?:SiteBlock[]};export type SiteSection=SiteBlock;
export type BusinessMode="store"|"services"|"portfolio"|"commerce_business"|"business_showcase"|"cv";
export type SectionField={key:string;label:string;type:"text"|"textarea"|"color"|"number"|"checkbox"|"url"|"select";options?:Array<{label:string;value:string}>};
export type ComponentMigration={from:number;migrate:(settings:ComponentSettings)=>ComponentSettings};
export type BlockPreset={name:string;settings?:ComponentSettings;blocks?:Array<{type:string;preset?:number}>};
type Base={type:string;name:string;version:number;presets:BlockPreset[];defaults:ComponentSettings;fields:SectionField[];migrations?:ComponentMigration[];blocks?:"@theme"|string[];maxBlocks?:number};
type ComponentProps={settings:ComponentSettings;blocks?:SiteBlock[]};
export type BlockDefinition=Base&{kind:"block";component:ComponentType<ComponentProps>};
export type GlobalDefinition=Base&{kind:"global";slot:"before"|"after";component:ComponentType<ComponentProps>};
export type SectionDefinition=Base&{kind:"section";category:"Essentials"|"Commerce"|"Services"|"Portfolio"|"CV";description:string;enabledOn?:BusinessMode[];component:ComponentType<ComponentProps>};
export type BlockModule={default:BlockDefinition};export type SectionModule={default:SectionDefinition};export type GlobalModule={default:GlobalDefinition};export type RegisteredComponent=SectionDefinition|BlockDefinition|GlobalDefinition;
